# Generated by Django 3.1.7 on 2021-04-08 19:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('reason', models.CharField(blank=True, choices=[('1', 'Лечебно-диагностический прием '), ('2', 'Консультативный прием '), ('3', 'Диспансерное наблюдение '), ('4', 'Профилактический прием'), ('5', 'Профессиональный осмотр'), ('6', 'Реабилитационный прием'), ('7', 'Зубопротезный прием'), ('8', 'Протезно-ортопедический прием'), ('9', 'Обращение в центр здоровья'), ('10', 'Дополнительная диспансеризация'), ('11', 'Патронаж'), ('12', 'Другие')], default='1', help_text='Повод обращения', max_length=2)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID пациента', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('patronym', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, choices=[('1', 'Мужской'), ('2', 'Женский'), ('3', 'Не определен')], default='1', help_text='Пол', max_length=1)),
                ('disability', models.CharField(blank=True, choices=[('1', '1 группа'), ('2', '2 группа'), ('3', '3 группа'), ('4', 'ребенок-инвалид')], default='1', help_text='Пол', max_length=1)),
                ('oms', models.CharField(help_text='Номер ОМС', max_length=20, verbose_name='ОМС')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('id_c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='id_p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.patient'),
        ),
    ]
