# Generated by Django 3.1.7 on 2021-09-13 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5e77a02-8444-4337-83f3-0adb4b4fc1ad'), help_text='ID случая', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d610169b-6bfe-4c9b-8d1d-5c17ebff8400'), help_text='ID пациента', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b1ed072-84a1-400a-91ba-ad7db0a337fb'), help_text='ID посещения', primary_key=True, serialize=False),
        ),
    ]
