# Generated by Django 3.1.7 on 2021-04-08 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['date'], 'verbose_name_plural': 'Случаи'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name'], 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['date'], 'verbose_name_plural': 'Посещения'},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата открытия'),
        ),
        migrations.AlterField(
            model_name='case',
            name='reason',
            field=models.CharField(blank=True, choices=[('1', 'Лечебно-диагностический прием '), ('2', 'Консультативный прием '), ('3', 'Диспансерное наблюдение '), ('4', 'Профилактический прием'), ('5', 'Профессиональный осмотр'), ('6', 'Реабилитационный прием'), ('7', 'Зубопротезный прием'), ('8', 'Протезно-ортопедический прием'), ('9', 'Обращение в центр здоровья'), ('10', 'Дополнительная диспансеризация'), ('11', 'Патронаж'), ('12', 'Другие')], default='1', help_text='Повод обращения', max_length=2, verbose_name='Повод обращения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disability',
            field=models.CharField(blank=True, choices=[('1', '1 группа'), ('2', '2 группа'), ('3', '3 группа'), ('4', 'ребенок-инвалид')], help_text='Группа инвалидности', max_length=1, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patronym',
            field=models.CharField(max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Мужской'), ('2', 'Женский'), ('3', 'Не определен')], help_text='Выберите пол', max_length=1, verbose_name='Пол'),
        ),
    ]
