# Generated by Django 3.1.7 on 2021-09-19 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210913_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.UUIDField(default=uuid.UUID('61559a4f-6f84-4169-b9ac-f88cc05cb3dd'), help_text='ID случая', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('622fdad7-9ed7-4375-879f-d808d20e0226'), help_text='ID пациента', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('13cf80ba-fae4-490b-8dcc-5077832d1795'), help_text='ID посещения', primary_key=True, serialize=False),
        ),
    ]
