# Generated by Django 3.1.7 on 2021-04-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_patient_smo'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='result',
            field=models.CharField(blank=True, choices=[('5', 'Здоров'), ('1', 'Выздоровление'), ('3', 'Без изменений'), ('2', 'Улучшение'), ('4', 'Ухудшение'), ('6', 'Летальный исход')], help_text='Исход случая', max_length=2, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='case',
            name='reason',
            field=models.CharField(blank=True, choices=[('1', 'Лечебно-диагностический прием '), ('2', 'Консультативный прием '), ('3', 'Диспансерное наблюдение '), ('4', 'Профилактический прием'), ('5', 'Профессиональный осмотр'), ('6', 'Реабилитационный прием'), ('7', 'Зубопротезный прием'), ('8', 'Протезно-ортопедический прием'), ('9', 'Обращение в центр здоровья'), ('10', 'Дополнительная диспансеризация'), ('11', 'Патронаж'), ('12', 'Другие')], help_text='Повод обращения', max_length=2, verbose_name='Повод обращения'),
        ),
    ]
