# Generated by Django 3.1.7 on 2021-09-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210919_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-date'], 'verbose_name': 'случай', 'verbose_name_plural': 'Случаи'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['-name'], 'verbose_name': 'Диагноз', 'verbose_name_plural': 'Диагнозы'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date'], 'verbose_name': 'посещение', 'verbose_name_plural': 'Посещения'},
        ),
        migrations.AddField(
            model_name='case',
            name='character',
            field=models.CharField(blank=True, choices=[('1', 'Впервые в жизни установленное хроническое'), ('2', 'Ранее установленное хроническое'), ('3', 'Острое')], help_text='Характер заболевания', max_length=2, verbose_name='Характер заболевания'),
        ),
        migrations.AddField(
            model_name='visit',
            name='help_type',
            field=models.CharField(blank=True, choices=[('10', 'Первичная медико-санитарная помощь'), ('1', 'Первичная доврачебная медико-санитарная помощь'), ('2', 'Первичная врачебная медико-санитарная помощь'), ('3', 'Первичная специализированная медико-санитарная помощь'), ('4', 'Специализированная медицинская помощь'), ('8', 'Высокотехнологичная специализированная медицинская помощь'), ('6', 'Паллиативная медицинская помощь'), ('5', 'Скорая медицинская помощь'), ('7', 'Иные')], help_text='Вид оказываемой помощи', max_length=2, verbose_name='Вид оказываемой помощи'),
        ),
        migrations.AlterField(
            model_name='case',
            name='diagnosis',
            field=models.ForeignKey(help_text='Выберите диагноз', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.diagnosis', verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(default=1, help_text='ID случая', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='id_p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.patient', verbose_name='ID пациента'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.CharField(help_text='Код болезни', max_length=20, primary_key=True, serialize=False, verbose_name='Код болезни(МКБ-10)'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(help_text='Название болезни', max_length=200, verbose_name='Название болезни(МКБ-10)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.AutoField(default=1, help_text='ID посещения', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.case', verbose_name='ID случая'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(default=1, help_text='ID услуги', max_length=9, primary_key=True, serialize=False, verbose_name='ID услуги')),
                ('service', models.CharField(help_text='Название услуги', max_length=200, verbose_name='Название услуги')),
                ('id_v', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.visit', verbose_name='ID посещения')),
            ],
            options={
                'verbose_name': 'услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
