# Generated by Django 3.1.7 on 2021-09-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210919_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='id_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(help_text='Код услуги', max_length=20, primary_key=True, serialize=False, verbose_name='Код услуги'),
        ),
    ]
