# Generated by Django 3.2 on 2021-04-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_pp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.visit'),
        ),
    ]
