# Generated by Django 3.1.7 on 2021-09-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210919_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id_v',
        ),
    ]
