# Generated by Django 3.1.7 on 2021-09-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_service_id_v'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='id_s',
            new_name='services',
        ),
    ]
