# Generated by Django 3.1.7 on 2021-05-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_person_id_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patronym',
            field=models.CharField(max_length=25, verbose_name='Отчество'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
