# Generated by Django 3.1.7 on 2021-09-19 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210919_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False, verbose_name='Дата посещения')),
                ('id_10_00', models.CharField(choices=[], max_length=50, null=True, verbose_name='10:00')),
                ('id_10_20', models.CharField(choices=[], max_length=50, null=True, verbose_name='10:20')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['-date'],
            },
        ),
    ]
