# Generated by Django 3.1.7 on 2021-09-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(help_text='ID случая', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(help_text='ID пациента', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.AutoField(help_text='ID посещения', primary_key=True, serialize=False),
        ),
    ]
