# Generated by Django 3.1.7 on 2021-09-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210919_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id_10_00',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='10:00'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id_10_20',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='10:20'),
        ),
    ]
