# Generated by Django 3.1.7 on 2021-09-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_mcd_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MCD',
            new_name='Diagnosis',
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.ManyToManyField(help_text='Выберите диагноз', to='catalog.Diagnosis'),
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis',
            field=models.ManyToManyField(help_text='Выберите диагноз', to='catalog.Diagnosis'),
        ),
    ]
