# Generated by Django 3.1.7 on 2021-09-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210913_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='reason',
            field=models.CharField(blank=True, choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], help_text='Повод обращения', max_length=20, verbose_name='Повод обращения'),
        ),
    ]
