# Generated by Django 3.1.7 on 2021-09-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210919_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-date'], 'verbose_name': 'Смену', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_10_40',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='10:40'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_11_00',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='11:00'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_11_20',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='11:20'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_11_40',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='11:40'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_13_00',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='13:00'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_13_20',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='13:20'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_13_40',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='13:40'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_14_00',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='14:00'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_14_20',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='14:20'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_14_40',
            field=models.CharField(choices=[('Андрей Васильев (1998-09-19) г.р.', 'Андрей Васильев (1998-09-19) г.р.'), ('Лев Тигров (2000-09-19) г.р.', 'Лев Тигров (2000-09-19) г.р.'), ('Лев Тигров2 (2000-09-19) г.р.', 'Лев Тигров2 (2000-09-19) г.р.')], max_length=50, null=True, verbose_name='14:40'),
        ),
    ]
