# Generated by Django 3.1.7 on 2021-09-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210913_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='id',
        ),
        migrations.RemoveField(
            model_name='case',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='case',
            name='diagnosis',
            field=models.ForeignKey(help_text='Выберите диагноз', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.CharField(help_text='Код болезни', max_length=20, primary_key=True, serialize=False),
        ),
    ]
